services:
  # -----------------------------------------------------------
  # PySpark
  # -----------------------------------------------------------
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./docker_shared_folder/working_dir:/home/dev/working_dir
    user: root
    working_dir: /home/dev/working_dir
    env_file:
      - ./docker_shared_folder/working_dir/.env
    environment:
      JUPYTER_ENABLE_LAB: '1' 
      JUPYTER_TOKEN: 'dev'
      NB_USER: dev
      NB_GID: 1000
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'
      SPARK_CLASSPATH: "/home/dev/working_dir/driver_jdbc/mysql-connector-j-8.0.32.jar:/home/dev/working_dir/spark_drivers/minio-7.1.0.jar:/home/dev/working_dir/spark_drivers/hadoop-aws-3.3.1.jar:/home/dev/working_dir/spark_drivers/aws-java-sdk-bundle-1.12.196.jar"
    networks:
      - data-network

  # -----------------------------------------------------------
  # MySQL
  # -----------------------------------------------------------
  mysql:
    hostname: mysql
    image: mysql:8.0.32
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: f1db
      MYSQL_USER: f1user
      MYSQL_PASSWORD: f1password
    ports:
      - "3307:3306"  # Mapeo el puerto 3307 en la máquina local al puerto 3306 dentro del contenedor
    volumes:
      - ./docker_shared_folder/working_dir/mysql_data:/var/lib/mysql
      - ./f1db.sql:/docker-entrypoint-initdb.d/f1db.sql
    networks:
      - data-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "f1user", "-pf1password"]
      interval: 5s
      timeout: 10s
      retries: 5
  
  # -----------------------------------------------------------
  # Trino
  # -----------------------------------------------------------
  trino:
    hostname: trino
    image: 'trinodb/trino:351'
    container_name: trino
    ports:
      - '8086:8080'
    volumes:
      - ./docker_shared_folder/working_dir/etc:/usr/lib/trino/etc:ro
    networks:
      - data-network

  # -----------------------------------------------------------
  # MariaDB
  # -----------------------------------------------------------
  mariadb:
    hostname: mariadb
    image: mariadb:10.5.8
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - data-network

  # -----------------------------------------------------------
  # Hive Metastore
  # -----------------------------------------------------------
  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    container_name: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./docker_shared_folder/working_dir/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - data-network

  # -----------------------------------------------------------
  # MinIO
  # -----------------------------------------------------------
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./docker_shared_folder/working_dir/data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - data-network

volumes:
  minio-data:
    driver: local

networks:
  data-network:
    driver: bridge
